---
title: “The role of community-based service organisations in the humanitarian response to infectious disease crises in vulnerable populations of sub-Saharan Africa”
subtitle: "for MGMT-5090"
author: "David Fong, daf422@g.harvard.edu"
format:
  html:
    toc: true
  pdf:
    toc: true
  docx:
    toc: true
    toc-depth: 3
    section-numbers: true
    reference-doc: custom-reference-doc.docx
editor: visual
csl: apa7.csl
bibliography: references.bib
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
# the following \pagebreak doesn't work unless there is some 'matter' after the front-matter!
```

\pagebreak

## Introduction

Infectious disease epidemic crises have repeatedly challenged the nations and peoples of sub-Saharan Africa. From HIV (1990s -- 2000s) to tuberculosis to Ebola (2014 -- 2016) and COVID-19 (2020 -- 2022), each emergent crisis -- sometimes originating in Africa, sometimes part of wider global pandemic and sometimes overlapping each other -- has presented novel and life-threatening landscape-scale threats to communities throughout sub-Saharan Africa [@kimani2020; @hasan2022]. Each infectious disease crisis has been characterised by novel difficulties in collecting information to inform situational awareness, sense-making, difficulties in formulating, implementing and adapting effective management plans, difficulties in disseminating information, widespread public fear and widespread social and economic impacts [@kevany2012]. Like other crises, infectious disease crises occur in an environment where no one is expert on all aspects [@boin2016; @leonard2009].

Effective healthcare response to infectious disease depends on the ability to deploy an available, well-trained and well-informed healthcare workforce. However, many of the countries in sub-Saharan Africa are -- and have been -- lacking in adequate healthcare resources [@cancedda2016; @paterson2017]. Weak governments, stagnant economies and neo-liberal policies have resulted in reduced expenditure on social services, such as healthcare [@okma2016]. The publicly-funded health sector often has weak governance and management systems [@internationalrescuecommittee2016]. Similarly, developing countries in Africa have limited resources to implement welfare and anti-poverty measures to mitigate the economic and social effects of an infectious disease epidemic and the adverse consequences of epidemic control measures [@gutierrez-romero2020]. In the face of gaps -- even during the absence of epidemic infections -- in government-provided social and healthcare services community-based (CBO) and other non-government (NGO) organisations have arisen to provide those services [@okma2016; @hushie2021].

In the midst of inadequate resources to manage the health, social and economic impacts of infectious disease epidemic crises, developing countries of sub-Saharan Africa face pre-existing endemic poverty [@gutierrez-romero2020]. With poverty comes many other high-priority health concerns, such as high rates of maternal and child mortality, chronic malnutrition and low levels of education [@sasidharan2021, p. 19]. These other concerns can easily divert attention away from infectious disease epidemic crises [@carstensen2021].

Infectious disease epidemics can, however, be anticipated. An increasing number of infections, often zoonotic, have crossed over into humans in the past two decades, and an increasing number of infections are expected to do so [@dvorak2020].

Since infectious disease epidemics and their health and social consequences can be anticipated and since community-based organisations (CBOs) already provide social and healthcare services then CBOs could potentially be well-positioned to assist in epidemic crisis responses.

It is increasingly recognized that response to major crises requires a whole of community engagement. Government organisations need to partner effectively with private, non-profit and community-based organisations to complement the public sector's own capabilities [@boin2016; @bedson2020].

This article will examine past and potential contributions of community-based organisations to the humanitarian response to infectious disease crises affecting vulnerable populations in sub-Saharan Africa.

## Infectious disease crises and social welfare

Infectious disease crises cause losses of social welfare [@vardavas2021; @leonard2010a]. Infectious disease outbreaks in sub-Saharan countries have caused loss of life, morbidity, reduction in individual economic prosperity, loss of education opportunity, destruction of skilled labour and loss of much-needed economic development [@boutayeb2010].

However, there are potential measures, including cost-effective measures, to reduce the loss of social welfare from infectious disease epidemics [@vardavas2021]. Potentially social welfare may even increase as the result of measures to improve community resilience [@australianbusinessroundtablefordisasterresilienceandsafercommunities2017]. Skill building, reducing the uncertainty of potential future losses and improved community connections can not only reduce the cost of a disaster but -- even in the absence of disaster -- improve social welfare.

## Reducing social welfare loss: the Comprehensive Risk Management Framework

@leonard2009a suggest that opportunities and measures to reduce social loss from disasters take place not only during and immediately after the disaster event, but also before the disaster event and during a (sometimes prolonged) recovery phase after the event.

-   Before the disaster event

    -   'Prevention/mitigation' -- Reduce the probability or severity of the event

    -   'Preparation for response' -- Prepare to respond rapidly and effectively to the event

    -   'Advance recovery' -- Prepare for a rapid, complete recovery, reducing the consequences of the event

-   During (and immediately after) the event

    -   'Response' -- Reduce the damage from the event, ministering to human needs

-   After the event

    -   'Recovery' -- Promote rapid, complete recovery. Restore social welfare.

Community-based organisations (CBOs) in sub-Saharan Africa have the potential and capability to assist in all stages of managing the risk of an infectious disease crisis. Examples of the role of CBOs in infectious crisis events follow.

### Prevention and mitigation

Ideally, infectious disease crises are prevented, or the number of infections reduced through mitigation.

CBOs are often already involved in reducing the risk of water-borne, vector-drive (e.g. mosquito) and sexually-transmitted disease outbreaks. Risk prevention and mitigation measures include providing education -- including about the nature and importance of infectious disease -- and enabling access to cleaner water and contraceptive services [@banerjee2012].

Measures taken to prevent or mitigate infectious from one epidemic may even have synergistic effects with other infection control programs. Hand-washing and better hygiene facilities built for the COVID-19 pandemic have reportedly led to decreased rates of cholera and typhoid in Kenyan communities [@carstensen2021].

### Response and preparation for response

The response to an infectious disease crisis, during the time of the crisis, reduces the damage from the crisis and also caters to human needs as the result of inflicted damage.

Infectious disease crises can directly cause death and morbidity among vulnerable populations. Death and morbidity of individuals places strain on the families and communities afflicted by infection, can have long-term effects (including nutritional, educational and earning potential) on affected individuals. Death and morbidity also affects the development of the community as a whole [@banerjee2012].

Communities already with socio-economic disadvantage are at increased vulnerability to infectious disease crises. The vulnerability is the result of reduced capacity to take measures to prevent infection, often increased susceptiblity to infection and reduced capacity to withstand the economic effects of either infection or measures taken to prevent infection [@bhaskar2020; @ahmed2020]. For example, local lockdowns to control COVID-19 increased riots, violence against civilians, food prices, food-related conflicts and food looting in Africa [@gutierrez-romero2020].

CBOs already have a role and resources to provide healthcare in sub-Saharan Africa. These resources can be utilised, potentially as 'surge-capacity', during a healthcare crisis [@hushie2021].

Other than directly providing healthcare or other human welfare services, CBOs may have other resources of value to improve crisis response. For example, crisis intervention services which are co--operating or co-located with CBO-provided services (such as food, development or skill-training) can improve service delivery to target communities which are already familiar or trust the CBO [@kevany2012].

CBOs can, and have, rapidly pivoted their own services towards provision of measures aimed at meeting immediate needs, even if outside the original scope of their operations. For example counselling services for HIV positive patients in Nairobi, Kenya, arranged food delivery to sex-workers during COVID-19 lockdowns [@ekeland2022; @kimani2020].

However, like other organisations which are not typically involved in crisis response, CBOs may have poor linkages and information sharing with other organisations, both government and non-governmental. Overcoming the lack of co-ordination is discussed under 'Challenges'.

### Recovery

CBOs have a role in support of infectious disease survivors and the families of both victims and survivors. Survivors may suffer post-infection social, economic, psychological and health challenges, as well as stigmatization [@hushie2021]. Similarly, the surviving families of infectious disease victims may suffer the consequences of ongoing poverty and psychological distress [@cho2018].

The role of CBOs in crisis recovery is aided by having presence in the community both before, and long after, the crisis [@internationalrescuecommittee2016]. The mere presence of CBO staff visiting households of isolated individuals and families for 'routine' visits could have mental health benefits [@carstensen2021].

### Preparing for recovery

The immediate response to an infectious disease crisis, and recovery from its effects, can be highly visible and demand immediate attention and considerable resources [@leonard2010a]. However, measures to enhance the response and recovery to an infectious disease epidemic conducted prior to an infectious disease crisis can also cost-effectively reduce the damage from the event and reduce the social welfare loss from the infectious disease event. Measures to prepare, in advance, for accelerated recovery can be particularly neglected [@leonard2010a].

General preparation for accelerated recovery can be relatively non-specific (compared to immediate responses to individual crises), and be generalised to different infectious disease, or even to other crises. CBOs with a strong level of 'ownership' by the community have the potential to improve the effectiveness of crisis responses by improving social trust and cohesion, improving community acceptance and participation in the response measures [@tiberghien2022]. CBOs, and the leadership of CBOs, can improve community self-reliance to identify challenges, develop strategies and mobilise resources (including external) to accelerate recovery [@leonard2010a].

For example, women and youth groups formed over common interests and communication, e.g. self-help groups and radio-listening groups in Burkina Faso, were quick to respond to infectious disease crises with spontaneous and volunteer-led mutual aid. These groups, with diverse representation, could be supported and encouraged to form long before a crisis [@carstensen2021].

## Benefits of involving CBOs in crisis response

### Local knowledge

Community-based organisations (CBOs) typically have local knowledge and presence, both before and after healthcare crises [@carstensen2021; @kieffer-døssing2020]. Already adapted to local conditions, they potentially have local situation awareness and insight into cultural beliefs. In particular, CBOs may have been established to assist or represent the interests of disadvantaged and powerless groups e.g. people living in informal settlements (slums), people living with HIV or sex-workers [@carstensen2021; @kimani2020].

### Diversity

A diversity of observations, opinions and approaches -- different to that of larger organisations and government organisations -- has the potential to improve situational awareness and provide effective response to complex humanitarian problems [@clarke2013].

Providing diversity of observation and opinion includes providing feedback on proposed interventions as applicable to specific people groups. CBOs can potentially monitor and anticipate unexpected and adverse consequences of policy through a feedback loop [@kevany2012]. For example, the advice to wash hands for twenty seconds to reduce the spread of COVID-19 provoked the response from a leader of a small community-based organisation in Kenya "Running water for 20 seconds! When we don't have even enough drinking water as it is" [@carstensen2021]. CBOs have the potential to enable or adapt responses to local conditions e.g. establishing hand-washing stations and exploring methods to wash hands with less water. The smaller size of CBOs may enable CBOs to respond more quickly and flexibly to crises than larger organisations [@hushie2021; @kieffer-døssing2020].

### Customising the message

CBOs can also customise and distribute messages into the local language and style of communication e.g. storytelling [@kieffer-døssing2020; @clulow2020; @ebolaou2015]. Girls in Kibera, Nairobi, Kenya (and, later, elsewhere in East Africa) adopted the small multi-coloured 'spike' haircut to publicize COVID-19 [@carstensen2021]. CBOs also countered local rumours e.g. regarding which populations were or weren't vulnerable to COVID-19 and rumours about treatments [@carstensen2021].

### Mobilise and empower

If they have strong connections to the community, CBOs can mobilise and empower communities through public education, including recruitment and training of local staff to aid in the humanitarian response [@hushie2021; @paterson2017]. Spontaneous local womens' groups in Burkina Faso -- after training -- going door-to-door raising awareness of COVID-19 related hygiene measures [@carstensen2021].

CBOs with a good community relations can improve co-operation and trust between the community and public authorities (e.g. hospitals) or non-governmental service providers [@hushie2021]. Particularly if the infection or interventions to prevent or control infection are contentious from a social, cultural or religious perspective e.g. HIV-AIDS [@kevany2012]. There may be new and developing therapies for treating infectious disease, but there may be high levels of community distrust in novel therapies. Communication between communities and bodies employing new therapies can help reduce that distrust [@bedson2020].

CBOs can provide an advocacy role for the community with the government authorities and other organisations [@carstensen2021].

### Resources

CBOs in sub-Saharan Africa have potential access to raise additional funds, both internationally and locally, other than what is available to the public authorities [@carstensen2021; @kimani2020; @hushie2021].

### Behaviour and iterative change

Behaviours drive infectious epidemic emergence and transmission. Crisis mitigation measures include enabling and reinforcing behaviour changes which reduce the spread of disease. Behaviour change education has traditionally been a one-way disease-focused communication from centralized experts [@bedson2020]. However, this may ineffective. For example, restrictions on movement and congregation may be considered a religious problem rather than a health problem in the Niger. Or closing schools may result -- in some communities -- in children gathering at the local river [@kieffer-døssing2020].

Communities can change behaviours, but need to be aware of the danger requiring behaviour change and mitigation strategies need to be available and palatable. This can be done through a two-way participatory learning and action approach to both create the 'demand' for behaviour change and the 'supply' of practical and realistic culturally-appropriate strategies [@bedson2020; @particip2017]. Development of strategies appropriate for the community -- guided by standardized, but flexible, operational processes -- can be done iteratively through questions such as [from @bedson2020]:

1\. What are the most commonly expressed disease-related concerns expressed by community members?

2\. What were the most commonly asked questions by community members?

3\. What did the community initially assess and rank as key risks for contracting the disease?

4\. What actions or by-laws have been (or can be) developed on the disease in this community?

Through iterations of consultation, monitoring, evaluation and feedback, community-based strategies can evolve over time to time-appropriate or more effective strategies e.g. from restricting movements into and out of a community to health surveillance of the community itself [@bedson2020].

In an HIV-intervention program working in sites including in South Africa, Tanzania and Zimbabwe, those sub-programs which included community consultation and participation (including consultation and operational co-operation with community-based organisations) had ten times higher intervention uptake compared to 'control' programs which did not have local adaptation [@kevany2012].

## Challenges

### Different modes of operation

Crisis response is not the routine business of CBOs. Crisis response requires a different mode of operation to 'business as usual'. For example, both public and private organisations typically devote more resources towards activities and few resources to gathering information, which is required to detect or monitor a potential crisis [@boin2016]. Staff, staff training, overall strategy and funding of CBOs are often all orientated and linked to typical development goals, slowing the ability of CBOs to provide crisis response services [@internationalrescuecommittee2016]. As a result, a CBO, like other organisations, may have difficulty flexibly adapting to needs of a crisis response [@leonard2009].

CBOs usual services, e.g. education, welfare support, may be disrupted by infectious disease measures. For example, awareness and educational programs, e.g. focusing on keeping girls in school and sexuality education, helped decrease HIV rates among African countries. However, during the COVID-19 epidemic, there was reduced HIV testing and ARV initiation in South Africa and even reduced access (50%) to ARV -- for those already on ARV treatment -- in Kenya [@hasan2022]. CBOs may need to take measures to adapt the provision of their usual services e.g. distribution of printed education material and assessment of same material in South Africa [@clulow2020].

### Communication and co-operation

The role and services provided by any individual CBO may be relatively narrow in scope and not reflect the comprehensive response required to a crisis [@carstensen2021]. A CBO's crisis response will often need to be supported and informed by expert external organisations.

However, CBOs may have poor linkages and information sharing with government, other large non-governmental organisations and other CBOs, reducing their ability to co-ordinate a comprehensive response. Government organisations may even be unwilling to acknowledge the potential or actual role of non-governmental organisations in crisis management and recovery [@colten2008].

Even worse, a multiplicity of organisations can result in confusing and contradictory messages. CBOs encompass a wide variety of organisations, each with different priorities, expertise and capacity [@hushie2021]. Behavioural change interventions are most likely to be effective if communication channels (world-of-mouth, social media, meetings, mass media) are co-ordinated with and in support of government policies [@bedson2020].

Co-ordination of government, NGOs and international aid can be assisted by the use of a national Incident Management Systems e.g. recruiting and training required staff, supplying required equipment, ensuring treatment centres are safe and co-ordination of systems [@paterson2017].

Co-ordination between CBOs and government can be improved by preparing -- prior to a crisis-response -- for CBO consultation, co-ordination and feedback directed towards adapting the crisis response [@kevany2012].

### Limited resources and sustainability

CBOs operating in a crisis environment can rapidly exhaust their limited resources [@carstensen2021]. Though CBOs can be well-placed to recruit community volunteers, the attrition and turnover rate of community volunteers can be high. Attrition can be reduced by appropriate compensation, perhaps funded by government or international agencies [@bedson2020].

Long-term sustainability of community-based mitigation measures is characterised by ongoing, continuously monitored actions e.g. monitoring of cases and morbidity, rather than one-off action items e.g. initial installation of a hand-washing station [@bedson2020].

## Conclusion

Community-based organisations can provide a decentralised, localised and adaptive responses to epidemic crises, but much can be done to prepare to strengthen the leadership and co-ordination in those responses [@clarke2014; @leonard2010].

\pagebreak

## References

::: {#refs}
:::
